### ISSUE TITLE
Streams are broken after 10 min

### ISSUE THREAD

**Issue by szobonyatomi** [dexterke/plugin.video.digi.hu-online#3]
Hi, 

first of all thank you and congrat for the addons.
It had been installed to an Xiaomi box (w/ Android Tv 6 os), everything works well until +- 10 mins, then the streams stop. Sometimes it comes back again with a few second buffering but usually the addon has been quit itself.

**Comment by dexterke** [comment]
This plugin is only a http wrapper. It acts like a web browser, it logs on to 'www.digionline.hu', retrieves the playlist URL and passes it on to Kodi for playback. The plugin does not control what happens afterwards.  Whatever happens after playback has started, simply cannot be the plugins fault.

I'm also a Xiaomi user (Mibox + Android TV 8.0.0 + Kodi 17) and I know how many problems it has, however the plugin works  - I could not see any issues with it so far. 

The problem you're describing is likely a Mibox, Kodi, WIFI or internet (bandwith) related issue, I think it's very likely that you should experience the same problem with other kodi plugins as well.

**Comment by szobonyatomi** [comment]
Thank you,

i have no idei, all the other addon work well, i will check soon with a new
fire tv stick 4k ;)



Dexterke <notifications@github.com> ezt írta (időpont: 2018. nov. 16., P,
20:14):

**Comment by dexterke** [comment]
I confirm the bug. The stream stalls ~12 minutes after Kodi playback has started.
I'm looking into the issue.

**Comment by szobonyatomi** [comment]
Ahh perfect,  thank you.
Good luck and thanks for your work! 
Regards

Tomi

**Comment by ghost** [comment]
hey!

really good stuff! I can also confirm the bug, but i'm sure you will find a workaround :) 

please keep us posted so we can also test!

everything else working great on OSMC

**Comment by gurabli** [comment]
Wonder if there is any update on this? Thanks

**Comment by ghost** [comment]
I would be also interested about the update, because for that 10min. it is pretty awesome! Hope you can make it :)

**Comment by dexterke** [comment]
Sorry guys,  I have no updates, it's the end of the year and I'm busy. I would really like to get to the bottom of this issue, I just haven't had time yet.

**Comment by dexterke** [comment]
I just pushed out a bugfix, please test the v0.1.1-beta version.

**Comment by szobonyatomi** [comment]
Thank you very much! It looks like perfect. 45 min no break!! Well done!

**Comment by ghost** [comment]
same here, tested for 20+ minutes, no breaks!!!

**Comment by gurabli** [comment]
Confirm working, excellent job! Thank you!

**Comment by dexterke** [comment]
OK, problem seems fixed now, closing issue
