### ISSUE TITLE
Addon for TarrTV?

### ISSUE THREAD

**Issue by gurabli** [dexterke/plugin.video.digi.hu-online#4]
Hi,
there is another provider in Hungary, TarrTV, who is a smaller provider, but they have some excellent list of channels, especially for sports. EPL and UCL can be watched mainly with them. Long story short, could you be so kind and check if their webtv can be also used to create a Kodi addon? Their app or web-based access doesn't provide any cast function, so it is not possible to cast live tv to TV, just PC or app.
I can give you a login to see and check if it can be somehow done. Maybe to open a new github repo for it?
Thanks

**Comment by dexterke** [comment]
really ?
