### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by hrobert20** [dexterke/plugin.video.digi.hu-online#5]
Hi, the addon stopped working for me because of failed SSL verification. I have tried on Krypton (17.6) and leia (18.5). Would you have any idea if this could be fixed in any way?

**Comment by dexterke** [comment]
Please provide more details. What exactly is not working, what device / platform are you using, version of Kodi, etc.. 
I just tested the plugin on my Desktop (Kodi v 18.5 on Ubuntu 16.04), MacBook (MacOS Mojave, Kodi 18.5) and it works fine. Only RTL Klub is broken, channel no longer working.

**Comment by dexterke** [comment]
@hrobert20 ? Can you provide some details ?

**Comment by hrobert20** [comment]
Sorry. Now it work for me as well. I think their SSL certification expired on the 6th January and they didn't renew it for a few days. All good now. Sorry for the false alarm :)
