### ISSUE TITLE
Quality Switch option

### ISSUE THREAD

**Issue by coreinsane** [dexterke/plugin.video.digi.hu-online#8]
**Is your feature request related to a problem? Please describe.**
I do not know how the implementation currently works of this addon. On the Web player and the Android player, there is an option in the Settings, to choose the stream quality, with an AUTO option, which chooses the highest available option, based on the user bandwidth. Sometimes it works great, and sometimes it chooses the lowest available option for no reason.

**Describe the solution you'd like**
I would like to have an option in the Addon settings in KODI, to be able to choose the quality of the stream, with the option to choose the highest available quality, and also an AUTO function.

**Describe alternatives you've considered**
If the implementation already chooses the highest available option, then you should ignore my feature request, and write something to the Readme.md about the current behavior.

**Additional context**
-

**Comment by dexterke** [comment]
@coreinsane FYI - The add-on is already hardcoded to request the high quality stream, I cannot imagine why anyone would ask medium or low quality (considering the shitty nature of the service), however, once the request is made, the quality is set by the remote server, not sure how to override that on the client side. Long story short, currently the add-on always requests the high quality stream, defaults to auto-mode,

**Comment by coreinsane** [comment]
@dexterke thank you very much for the explanation, you can close this feature request. I would be glad to see this behaviour mentioned in the Readme.md :)
